import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import BottomNavbar from '@/components/organisms/BootomNavbar'
import { Toaster } from 'sonner';


const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Toaster position="top-center" />
             {children}
             <BottomNavbar/>
           </body>
      </html>
  )
}
